project_id = "rose-by-marry"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://rosebymarry.com"
additional_redirect_urls = ["http://localhost:8080"]

[auth.email]
enable_signup = false
