import fs from 'fs';
import pkg from 'jsdom';
import { fileURLToPath } from 'node:url';
const PUB = fileURLToPath(new URL('../public', import.meta.url));
const { JSDOM, VirtualConsole } = pkg;
const sleep = ms => new Promise(r => setTimeout(r, ms));
const A = (n, c) => { console.log((c ? 'PASS' : 'FAIL') + ' | ' + n); if (!c) process.exitCode = 1; };
const html = fs.readFileSync(PUB + '/index.html', 'utf8');
const SEED = { settings: { whatsapp: '212772966980', currency: 'DH', siteUrl: '', passHash: null, freeShip: 500, builderUnit: 9 }, categories: [{ id: 'bouq', icon: '', ar: 'باقات', fr: 'B', en: 'B' }], products: [{ id: 'amour', cat: 'bouq', type: 'bouquet', qty: 10, ar: 'أ', fr: 'B', en: 'A', dar: '', dfr: '', den: '', price: 90, old: 0, badge: '', featured: true, active: true }], colors: [{ id: 'red', ar: 'أحمر', fr: 'R', en: 'R', hex: '#C8102E', available: true }], addons: [], builderTiers: [{ id: 'b5', qty: 5, price: 45 }], zones: [{ id: 'tanger', ar: 'ط', fr: 'T', en: 'T', fee: 20 }], promoCodes: [], discounts: [], reviews: [], orders: [], pageviews: {}, prodViews: {} };
const mk = storage => { const vc = new VirtualConsole(); return new JSDOM(html, { url: 'http://localhost:8080/', runScripts: 'dangerously', resources: 'usable', pretendToBeVisual: true, virtualConsole: vc, beforeParse(w) { w.localStorage.setItem('rbm_v2_state', JSON.stringify(SEED)); if (storage) for (const [k, v] of Object.entries(storage)) w.localStorage.setItem(k, v); } }); };
let dom = mk(null); await sleep(1400);
let d = dom.window.document;
A('default: dark (no data-theme attr)', !d.documentElement.hasAttribute('data-theme'));
A('toggle button in navbar with svg icon', !!d.getElementById('themeBtn') && !!d.getElementById('themeBtn').querySelector('svg'));
d.getElementById('themeBtn').click(); await sleep(120);
A('click: html[data-theme=light]', d.documentElement.getAttribute('data-theme') === 'light');
A('click: persisted rbm_theme=light', dom.window.localStorage.getItem('rbm_theme') === 'light');
A('click: theme-color meta -> #FFFFFF', d.querySelector('meta[name="theme-color"]').getAttribute('content') === '#FFFFFF');
A('click: icon swapped to moon', !!d.getElementById('themeBtn').querySelector('svg path[d^="M21 12.8"]'));
d.getElementById('themeBtn').click(); await sleep(120);
A('toggle back: dark + saved', !d.documentElement.hasAttribute('data-theme') && dom.window.localStorage.getItem('rbm_theme') === 'dark');
dom.window.close();
dom = mk({ rbm_theme: 'light' }); await sleep(1400);
d = dom.window.document;
A('reload: light restored instantly (no-flash script)', d.documentElement.getAttribute('data-theme') === 'light');
dom.window.close();
const ah = fs.readFileSync(PUB + '/admin/index.html', 'utf8');
A('admin: no theme toggle, theme scoped out', !ah.includes('themeBtn') && !ah.includes('rbm_theme'));
console.log('--- theme suite done');
process.exit(process.exitCode || 0);
