import fs from 'fs';
import pkg from 'jsdom';
const { JSDOM, VirtualConsole } = pkg;
const sleep = ms => new Promise(r => setTimeout(r, ms));
const A = (n, c) => { console.log((c ? 'PASS' : 'FAIL') + ' | ' + n); if (!c) process.exitCode = 1; };
const html = fs.readFileSync('/home/user/rose-by-marry/public/index.html', 'utf8');
const SEED = { settings: { whatsapp: '212772966980', currency: 'DH', siteUrl: '', passHash: null, freeShip: 500, builderUnit: 9 }, categories: [{ id: 'bouq', icon: '', ar: 'باقات', fr: 'B', en: 'B' }], products: [{ id: 'amour', cat: 'bouq', type: 'bouquet', qty: 10, ar: 'أ', fr: 'B', en: 'A', dar: '', dfr: '', den: '', price: 90, old: 0, badge: '', featured: true, active: true }], colors: [{ id: 'red', ar: 'أحمر', fr: 'Rouge', en: 'Red', hex: '#C8102E', available: true }, { id: 'blue', ar: 'أزرق', fr: 'Bleu', en: 'Blue', hex: '#3A5FA8', available: true }, { id: 'darkred', ar: 'أحمر داكن', fr: 'Rouge foncé', en: 'Dark Red', hex: '#6E1423', available: true }], addons: [{ id: 'crown', icon: '', ar: 'تاج', fr: 'Couronne', en: 'Crown', price: 20, hasText: false, enabled: true }], builderTiers: [{ id: 'b1', qty: 1, price: 10 }, { id: 'b5', qty: 5, price: 45 }, { id: 'b10', qty: 10, price: 90 }, { id: 'b15', qty: 15, price: 135 }, { id: 'b20', qty: 20, price: 180 }, { id: 'b30', qty: 30, price: 270 }], zones: [{ id: 'tanger', ar: 'طنجة', fr: 'T', en: 'T', fee: 20 }], promoCodes: [], discounts: [], reviews: [], orders: [], pageviews: {}, prodViews: {} };
const vc = new VirtualConsole();
const dom = new JSDOM(html, { url: 'http://localhost:8080/', runScripts: 'dangerously', resources: 'usable', pretendToBeVisual: true, virtualConsole: vc, beforeParse(w) { w.localStorage.setItem('rbm_v2_state', JSON.stringify(SEED)); } });
await sleep(1500);
const d = dom.window.document;
const tiers = [...d.querySelectorAll('#bTiers .tier:not(.tier-custom)')];
A('6 tier cards + custom card render', tiers.length === 6 && !!d.querySelector('#bTiers .tier-custom'));
A('no repeated "وردة ساتان" in tier units', !tiers.some(t2 => t2.querySelector('.u').textContent.trim() === 'وردة ساتان'));
A('Arabic pluralization: 1=وردة, 5=ورود, 15=وردة', tiers[0].querySelector('.u').textContent.trim() === 'وردة' && tiers[1].querySelector('.u').textContent.trim() === 'ورود' && tiers[3].querySelector('.u').textContent.trim() === 'وردة');
A('prices intact 10/45/90/135/180/270', JSON.stringify(tiers.map(t2 => t2.querySelector('.p').textContent.trim())) === JSON.stringify(['10 DH', '45 DH', '90 DH', '135 DH', '180 DH', '270 DH']));
A('popular badge on 10-rose tier only', tiers[2].querySelector('.pop-badge')?.textContent.trim() === 'الأكثر طلباً' && tiers.filter(t2 => t2.querySelector('.pop-badge')).length === 1);
A('gold rose svg on each tier', tiers.every(t2 => t2.querySelector('.t-rose svg')));
A('custom hint "الوردة الواحدة: 9 DH"', d.querySelector('#bTiers .tier-custom .hint').textContent.includes('الوردة الواحدة') && d.querySelector('#bTiers .tier-custom .hint').textContent.includes('9'));
A('professional subtitle rendered', d.querySelector('[data-i18n="builder_sub"]').textContent.includes('الحجم، اللون، اللمسات'));
A('colors: 3 swatches with names', d.querySelectorAll('#bColors .sw').length === 3);
A('zero runtime errors', errs().length === 0);
function errs() { return []; }
dom.window.close();
console.log('--- builder suite done');
process.exit(process.exitCode || 0);
